[I2C]
ADDR_B = 0x38
ADDR_A = 0x21

[ADC]
THRESHOLD_VOLTAGE = 1.7
POLLING_DELAY = 0.02
ENABLE_PEAK_DETECTOR = 0

[BTN]
MODE = 2
#0 - Polling
#1 - Polling with software debounce
#2 - Polling with hardware and software debounce
#3 - Interrupt
IDLE_POLLING_DELAY = 0.5
DEBOUNCE_POLLING_DELAY = 0.05
DEBOUNCE_STABLE_PERIOD = 0.5
DEBOUNCE_WAIT_NEXT_PRESS = 3.0

[PID]
KP = 6.0
KD = -0.6
KI = 1.0
TARGET_LUMINOSITY = 1.1
MAX_OUTPUT = 10.0
MIN_OUTPUT = 1.0
POLLING_DELAY = 0.4

[GPIO]
SERVO_PWM = 10
SERVO_POWER = 9
BUTTON_INT = 11
BUZZER_FREQUENCY = 110
BUZZER_PWM = 8

[GENERAL]
ENABLE_COUNTDOWN = 1


